- candidate-schema.json
- candidates/dhis2.json
- candidates/gdl.json
- candidates/met_norway_weather.json
- candidates/wikipedia.json
Simplified the types of DPGs to `software`, `data` and `standards`, and updated the existing candidate files.
> BLD: updated schema

- candidates/ba_obras.json
Adding the [BA Obras](https://github.com/datosgcba/ba_obras) project, but waiting to resolve [this issue](https://github.com/datosgcba/ba_obras/pull/2) to include the license.
> BLD: BA Obras

- candidates/cropplanning.json
Adding a candidate for [CropPlanning](https://github.com/claytonrcarter/cropplanning), but waiting for [this issue](https://github.com/claytonrcarter/cropplanning/issues/12) to resolve, and a license to be added to the project.
> BLD: +cropplanning

- candidates/mUzima.json
Please review and add mUzima.  Thanks!
> Adding mUzima

- nominees/feed-the-monster.json
Moving [this PR](https://github.com/unicef/publicgoods-website/pull/1) from another repo here where it belongs
> BLD: add Feed The Monster

- nominees/h5p.json
Adding a representative repo for H5P to show activity.
> BLD: added subrepo link to H5P

- nominees/magma.json
Added Facebook's [Magma](https://engineering.fb.com/open-source/magma/)
> BLD: added magma

- nominees/ekitabu.json
- nominees/marytts.json
- nominees/muckrock.json
- nominees/octopus-microfinance.json
- nominees/odoo.json
- nominees/open-bank-project.json
- nominees/opencbs.json
- nominees/openrefine.json
- nominees/reconcile-cvs.json
- nominees/safe-open-source-microfinance-suite.json
- nominees/x-road.json
> Adding a set of nominees related to financial inclusion

- CHANGELOG.md
- nominees/recordtrac.json
See https://github.com/codeforamerica/recordtrac
> BLD: +recordtrac

- CHANGELOG.md
- nominees/smart-kyc.json
Adding another nominee in the financial inclusion space.
> BLD: added smart-kyc

- CHANGELOG.md
- nominees/dspace.json
> BLD: added DSpace

- CHANGELOG.md
- nominees/hapi-fhir.json
> BLD: added HAPI FHIR

- CHANGELOG.md
- nominees/project-catalog-management-tool.json
See https://pcmt.gitlab.io/website/
> BLD: added PCMT

- CHANGELOG.md
- nominees/openach.json
> BLD: added openACH

- CHANGELOG.md
- nominees/mit-climate-primer.json
> BLD: addded MIT Climate Primer

- CHANGELOG.md
- nominees/lockdown-learning-repository.json
> BLD: added Lockdown Learning Repository

- nominees/meilisearch.json
Cc: @bidoubiwa, @curquiza, @eskombro, @Kerollmops, @qdequele, @tpayet
> BLD: add MeiliSearch

- CHANGELOG.md
- nominee-schema.json
- nominees/code.etalab.gouv.fr.json
> BLD: add code.etalab.gouv.fr.json

- CHANGELOG.md
- nominees/oer-plan-ceibal-uruguay.json
> BLD: add oer-plan-ceibal-uruguay.json

- nominees/typescript.json
- nominees/webpack.json
Thank you for this great initiative 🙏
I'd like to nominate Typescript & webpack, which I believe both are very critical in web development field.
Please let me know if you need any additional information about these projects.
> Typescript & webpack nominations

- nominees/oer-plan-ceibal-uruguay.json
Propagating the changes from publicgoods/products#37. 
I was waiting to implement #57, so that now I can `[skip pr]` and prevent the automatic opening a PR back to that repo 🙌
> MAINT: updated licenses for plan ceibal [skip pr]

- CHANGELOG.md
Release v0.5.0, see `CHANGELOG.md` for changes
> MAINT: release v0.5.0

- CHANGELOG.md
- nominees/gdl-radio.json
Cc: @livmarte, @christer-io, @Lucyeoh
> BLD: added gdl-radio.json

- nominee-schema.json
> BLD: added SDGevidence to schema [skip pr]

- screening-schema.json
Modified screening schema for remaining data driven form pages
> Modified screening schema

- screening/opencrvs-submission.json
- screening/opencrvs.json
Migrate OpenCRVS submission data to JSON
> Migrate OpenCRVS submission data to JSON

- screening/primero-migration.json
- screening/primero.json
Migrated submission data for Primero
> Migrated submission data for Primero

- CHANGELOG.md
- nominees/global-open-facility-registry.json
As per conversations with Digital Square and UNICEF Eastern and Southern Africa Regional Office (ESARO), as that is how this project is known.
> Rename facility-reconciliation-tool to global-open-facility-registry (GOFR)

- CHANGELOG.md
- nominees/mobile-wach.json
Added Mobile-WACh, as vetted by Digital Square as a Global Good [here](https://wiki.digitalsquare.io/index.php/Main_Page). Have been missing the repo link for a while...
> BLD: added mobile-wach.json

- CHANGELOG.md
- nominees/geoprism-registry.json
Added Geoprism Registry (Common Geo-Registry) as reported by @seanblaschke
> BLD: added geoprism-registry

- screening/apache-fineract.json
Migrate Apache Fineract submission data to JSON
> Migrate Apache Fineract submission data to JSON

- nominees/hippocratic-license.json
> Add nominee: Hippocratic License

- nominees/geomancer-an-open-source-framework-for-geospatial-feature-engineering.json
- nominees/geomancer.json
> Add nominee: Geomancer: An Open-Source Framework for Geospatial Feature Engineering

- nominees/global-open-facility-registry.json
- nominees/openg2p.json
> Add nominee: OpenG2P

- nominee-schema.json
- nominees/ai-powered-poverty-estimation.json
> Add nominee: AI Powered Poverty Estimation

- screening/mojaloop.json
Encode the Mojaloop submission into JSON and add it to unicef/publicgoods-candidates/screening
> Encode the Mojaloop submission into JSON 

- screening-schema.json
Corrected small typo in `screening-schema.json`
> MAINT: small typo

- nominees/mojaloop.json
- screening/mojaloop.json
Updated Mojaloop screening information for SDGs relevance and added another link on ownership documentation which highlights copyright info.
> Mojaloop screening update

- nominees/apache-fineract.json
Updated SDG evidenceURL to list of SDGs for Apache Fineract.
> Updated SDG evidenceURL to list of SDGs for Apache Fineract

- nominees/african-terrestrial-fibre-network-mapping-project-(afterfibre).json
- nominees/african-terrestrial-fibre-network-mapping-project.json
> Add nominee: African Terrestrial Fibre Network Mapping Project (AfTerFibre)

- nominees/dhis2.json
- screening/dhis2.json
Encode DHIS2 submission into JSON and add it to unicef/publicgoods-candidates/screening.
> Encode DHIS2 submission into JSON 

- nominees/global-digital-library.json
Removed software tag from Global Digital Library nominee submission.
> Removed software tag from Global Digital Library nominee submission

- nominees/mojaloop.json
Updated `Mojaloop` status from `nominee` to `DPG`.
> Update Mojaloop status from nominee to DPG

- nominees/avyantra-health-technologies.json
Avyantra health technologies nominee update.
> Avyantra health technologies nominee update

- nominees/civicrm.json
> Add nominee: CiviCRM

- nominees/humansis.json
> Add nominee: Humansis

- screening-schema.json
> Propagate the changes from DPG-Standard to screening-schema.json

- nominees/the-atrium.json
Manually add nominee: The Atrium
> Manually add nominee: The Atrium

- nominees/commcare-android.json
- nominees/commcare-cloud.json
- nominees/commcare.json
> Add nominee: CommCare

- nominees/juniper.json
> Add nominee: Juniper

- reviews/Mojaloop-guiflor.json
> public-goods-candidates

- reviews/OpenCRVS-guiflor.json
> unicef-public-goods-candidates-1

- reviews/Avyantra Health Technologies-upretiprateek.json
> Add review

- .github/workflows/main.yml
- package-lock.json
- package.json
- scripts/api.js
Updates API for Digital Public Goods, refer to [publicgoods-api repo](https://github.com/unicef/publicgoods-api).
Includes GitHub Actions workflow to automatically push an update for every commit to master that introduces any change in `nominees/` or `screening/` files.
Initially developed using [nodegit](https://www.nodegit.org/) library, it proved to be unnecessarily overly complicated, and that library documentation was not very user friendly. Switch over to [isomorphic-git](https://isomorphic-git.org/), which proved to be the right library for the job.
All the testing for this script has been done on a fork of this repo. See [this build](https://github.com/lacabra/publicgoods-candidates/runs/1823511472#step:5:7) that triggered [this …
> BLD: autogenerate API

- screening-schema.json
- screening/apache-fineract.json
- screening/avyantra-health-technologies.json
- screening/dhis2.json
- screening/mifos-community-app.json
- screening/modular-open-source-identity-plaform.json
- screening/mojaloop.json
- screening/opencrvs.json
- screening/openg2p.json
- screening/primero.json
- screening/x-road.json
Renamed the above 2 indicators cascaded changes from screening-schema to all screened DPGs.
> Renamed 2 indicators: Clear Ownership & Platform Independence

- screening-schema.json
- screening/apache-fineract.json
- screening/avyantra-health-technologies.json
- screening/dhis2.json
- screening/met-norway-weather-api.json
- screening/mifos-community-app.json
- screening/modular-open-source-identity-plaform.json
- screening/mojaloop.json
- screening/opencrvs.json
- screening/openg2p.json
- screening/primero.json
- screening/vips.json
- screening/x-road.json
Propagate suggested change in indicator 7.
> Propagate suggested change in indicator 7

- nominees/bahmni.json
- screening/bahmni.json
Encode Bahmni full submission into JSON.
> Encode Bahmni full submission into JSON

- CONTRIBUTING.md
Updated the SDGs field to contain an array of objects having properties such as  `SDGNumber`, `evidenceText` and `evidenceURL`.
Added `stage` field to the template.
> updated SDGs field and added stage field in Template section

- nominees/glific.json
> Add nominee: Glific

- nominees/collect-earth.json
> Add nominee: Collect Earth

- nominees/wikigender.json
> Add nominee: Wikigender

- CONTRIBUTING.md
Documents that at least `evidenceText` or `evidenceURL` is required for each SDG entry.
> DOC: Updated CONTRIBUTING

- nominees/nomie.json
Hi, Im an outreachy applicant. I found a great open-sourced life-tracker app that don't collect, sell, use or track user's private data. There are no central servers, there's no nomie account.
> add nominees: open-sourced life-tracker Nomie

- scripts/open_pr.js
This resolves issue #311 
1) Created a generalized function to make API calls(POST, GET, DELETE)
2) Creating commits for files that are deleted.
> CI: open_pr implemented to handle deleted files

- README.md
This is a contribution for the open-ended issue in #473. When I first read the ReadMe, I was a little unclear as to what counts as a Digital Public Good. I have added the definition so that new contributors find it easier to understand.
> Add definition of DPG in ReadMe

- nominees/emoncms.json
Emoncms is an open-source web application for processing, logging and visualizing energy, temperature and other environmental data. It is a part of the OpenEnergyMonitor project. It helps users understand energy, explore the context of renewable energy and zero carbon.
> add nominee: Emoncms

- nominees/openems.json
OpenEMS is a modular platform for energy management applications. It was developed around the requirements of controlling, monitoring and integrating energy storage systems together with renewable energy sources and complementary devices and services.
> add nominee: Open Source Energy Management System

- nominees/safecast.json
Safecast is an international volunteer driven non-profit organization whose goal is to create useful, accessible, and granular environmental data. All Safecast data is published, free of charge, into the public domain under a CC0 designation.
Safecast covers 8 SDGs
> add nominee: Safecast

- nominees/high-resolution-population-density-estimates.json
> Add nominee: High Resolution Population Density Estimates

- nominees/project-sidewalk.json
> Add nominee: Project Sidewalk

- nominees/brainflow.json
With BrainFlow neuroscientists or other users can obtain, parse and analyze electrical brain activity (EEG), muscle activity (EMG), heart rate (ECG) and other kinds of data from biosensors. For example, it can help develop tools and software for people with disabilities.
> add nominee: BrainFlow

- .github/workflows/main.yml
As per the archival of [publicgoods/products](https://github.com/publicgoods/products/)documented in publicgoods/products#159, the automatic opening of pull requests against that repository is being disabled.
> MAINT: disable open_pr CI

- nominees/kobotoolbox.json
> Update nominee: KoboToolbox

- nominees/avyantra-health-technologies.json
Update status of `Avyantra Health Technologies` from `nominee` to `DPG`
> Update nominee: Avyantra Health Technologies 

- nominees/project-aedes.json
> Update nominee: project AEDES

- digitalpublicgoods/opensrp.json
- nominees/opensrp.json
Encode `OpenSRP` full submission into `JSON`
> Encode OpenSRP full submission into JSON

- digitalpublicgoods/global-open-facility-registry.json
- nominees/global-open-facility-registry.json
Encode `GOFR` full submission into `JSON`
> Encode GOFR full submission into JSON

- digitalpublicgoods/opensrp.json
Update `OpenSRP` copyright & trademark information
> Update OpenSRP copyright & trademark information

- nominees/safe-you.json
> Update nominee: Safe YOU

- nominees/odk.json
Update `ODK` `status` from `nominee` to `DPG`
> Update nominee: ODK

- nominees/rapidpro.json
> Update nominee: RapidPro

- nominees/open-risk-manual.json
This PR replaces #604, which was closed due to faulty branch name auto generated.
> Add nominee: Open Risk Manual

- nominees/meron.json
Add nominee: `Methods for Extremely Rapid Observation of Nutritional Status`
> Add nominee: MERON

- nominees/care.json
- nominees/coronasafe-care.json
> Add nominee: Coronasafe Care

- nominees/fedora-linux.json
> Add nominee: Fedora Linux

- nominees/coronasafe-care.json
- nominees/elimu.ai.json
- nominees/fao-digital-services-portfolio-agrimarketplace.json
- nominees/fao-digital-services-portfolio-e-nutrifood.json
- nominees/fao-digital-services-portfolio-livestock.json
- nominees/fao-digital-services-portfolio-weather-and-crop-calendar.json
- nominees/open-terms-archive.json
- nominees/statbus.json
- nominees/vrapeutic.json
Add nominee: `Open Terms Archive`
> Add nominee: Open Terms Archive

- nominees/standard-for-public-code.json
Update status from `nominee` to `DPG`
> Update nominee: Standard For Public Code

- nominees/glific.json
Update SDG 17 `evidenceURL` field
> Update nominee: Glific

- nominees/standard-for-public-code.json
Added link to the github repository, in hope that it will make
the contributions graph show in the registry.
> Add link to Standard for Public Code repository

- nominees/oscar.json
Add nominee: `Observing Systems Capability Analysis and Review Tool (OSCAR)`
> Add nominee: OSCAR

- digitalpublicgoods/altinn.json
- nominees/altinn.json
> Add DPG: Altinn

- digitalpublicgoods/meron.json
- nominees/meron.json
Add DPG: `MERON (Methods for Extremely Rapid Observation of Nutritional Status)`
> Add DPG: MERON

- digitalpublicgoods/glific.json
- nominees/glific.json
Works towards unicef#555, may need some cleanup.
( created with https://github.com/ericherman/dpg-csv-to-json )
> Add DPG: Glific

- nominees/oky.json
> Remove leading whitespace in name field

- nominees/productive-forests.json
> Add nominee: Productive Forests

- nominees/cloudline-unicef-services.json
- nominees/cloudline.json
> Add nominee: Cloudline 

- nominees/portableutm.json
> Add nominee: PortableUTM

- nominees/coronasafe-care.json
Update status from `nominee` to `DPG`
> Update DPG: Coronasafe Care

- nominees/ottaa-project.json
> Add nominee: OTTAA Project

- README.md
- docs/help-center.md
- docs/help-center/best-practices.md
- docs/help-center/documentation.md
- docs/help-center/open-standards.md
The Help Center Guide contains several tips to provide insights on a few ambiguous DPG standard indicators to projects making full submissions:
> Add Local Help Guide: Help Center

- nominees/ai-agro.json
> Updated DPG: AI Agro

- docs/help-center/open-standards.md
Update data exchange open standards: add `TIFF` & `RDF`
> Update data exchange open standards

- docs/help-center/best-practices.md
Update best practices: add `material design` item to `UI/ UX`
> Update best practices: add material design to UI/ UX

- nominees/find-your-immunization.json
> Add nominee: Find Your Immunization

- nominees/python-package-index.json
> Add nominee: Python Package Index

- nominees/project-konko.json
Updated status from `nominee` to `DPG`
> Updated DPG: Project Konko

- nominees/openfn-integration-toolkit.json
> Add nominee: OpenFn Integration Toolkit

- scripts/push.bash
Complementary to unicef/publicgoods-scripts#71: automates the generation of the interactive roadmap so that the CI can add it to the website snapshot.
> BLD: add interactive roadmap to website

- nominees/edunoss.json
Updated website as requested by product owner over email
> MAINT: updated website for EduNOSS

- nominees/human-essentials.json
As a result of unicef/publicgoods-scripts@8457ce5fed232685440a7fd5c53424cc34c7e949 several repositoryURLs have been updated.
> MAINT: updated various repoURLs

- nominees/victimsofintolerance.json
Add nominee: `VictimsOfIntolerance`
Continuing from #739
> Add nominee: VictimsOfIntolerance

- nominees/book-dash.json
> Update nominee: Book Dash

- nominees/somleng.json
- Updated `license` & `repository` URLs
> Update nominee: Somleng

- nominees/open-referral.json
> Add nominee: Open Referral

- excluded-nominees/README.md
- excluded-nominees/project-kick-out-covid-19-infotech.json
- nominees/project-kick-out-covid-19-infotech.json
> Add nominee: project-kick-out-covid-19-infotech

- nominees/accessible-kazakhstan.json
- Update status from `nominee` to `DPG`
> Update status: Accessible Kazakhstan

- nominees/prism.json
Resolves merge failure on PR #570
> Add nominee: PRISM

- digitalpublicgoods/open-foris-collect.json
- nominees/open-foris-collect.json
> Add DPG: Open Foris Collect

- nominees/santeims.json
> Add nominee: SantéIMS

- nominees/kindly.json
> Add nominee: Kindly

- nominees/santempi.json
> Add nominee: SantéMPI

- nominees/sunbird-quml.json
> Update nominee to DPG: Sunbird QuML

- nominees/digit.json
- nominees/digital-infrastructure-for-governance-impact-and-transformation.json
> Add nominee: DIGIT

- nominees/kindly.json
> Add DPG: Kindly

- scripts/api.js
- scripts/open_pr.js
- scripts/push.bash
Adjusts configuration as a result of migrating several `publicgoods-*` repositories from `UNICEF` to `DPGAlliance` and changes user from `lacabra` to `dpgabot`
> MAINT: organization migration unicef->DPGA

- docs/help-center/best-practices.md
- Add [SOLID](https://www.freecodecamp.org/news/solid-principles-explained-in-plain-english/) principles of OOP & `code review` to `architectural design` &`software development` categories respectively.
> Update best practices resources

- digitalpublicgoods/pxweb.json
- Update adherence steps - include terms of use for `PxWeb`
> Update DPG: PxWeb

- digitalpublicgoods/globaleaks.json
- Updated best practices & open standards indicators.
> Update DPG: Globaleaks

- docs/help-center/best-practices.md
-  Added [open source tips](https://eddiejaoude.github.io/book-open-source-tips/) to open source category
> Update best practices list 

- nominees/ur-scape.json
- Update project name from `Urban Rural Systems` to `ur-scape`
- Update funding organizations - add `Asian Development Bank (ADB)` and `Swiss State Secretary for Economic Affairs (SECO)` to list.
> Rename nominee: Urban Rural Systems

- nominees/lily-the-llama-helps-her-herd.json
Update status to DPG following approval on #613
> Update status: Lily the Llama Herds Her Herd

- excluded-nominees/README.md
Fix ordering of excluded nominees in README.md
> [MAINTENANCE] Fix ordering of excluded nominees in README.md

- nominees/epirust.json
> Update nominee: epiRust

- nominee-schema.json
Added new `stage` to [nominee schema](https://github.com/DPGAlliance/publicgoods-candidates/blob/main/nominee-schema.json): `archive`
> Add stage: archive

- nominees/2019-ncov-data-repository-by-johns-hopkins-csse.json
- nominees/2020policebrutality.json
- nominees/5calls-frontend.json
- nominees/5calls-ios.json
- nominees/aarogya-setu.json
- nominees/accessibility-cloud.json
- nominees/adopt-a-drain.json
Move nominees without contact information to archive
> [MAINT] Move nominees without contact information to archive

- digitalpublicgoods/x-road.json
Update privacy security description
> Re-review DPG: X-road

- digitalpublicgoods/opencrvs.json
- nominees/opencrvs.json
> Re-review DPG: OpenCRVS

- archive/alex-atom-linter.json
- archive/alex-sublime-linter.json
- archive/alex.json
- archive/android-guides.json
- archive/apache-ctakes.json
- archive/api.gouv.fr.json
- archive/arkhn-fhir-pipe.json
- archive/ask.json
- archive/askdarcel-api.json
- archive/askdarcel.json
> Archive projects

- nominees/zamba.json
> Update status: Zamba

- nominees/if-me.json
> Update nominee: If me

- nominees/reveal.json
> Update nominee: Reveal

- nominees/openimis.json
> [HOTFIX] Replace OpenIMIS

- nominees/sunbird-obsrv.json
> Update nominee: Sunbird Obsrv

- nominees/growstuff.json
Resolve conflicting files on #1100
> Add nominee: Growstuff

- nominees/mojaloop.json
> Update DPG: Mojaloop

- docs/help-center/open-standards.md
- Update open standards - IEEE Digital Reality standards
> Update open standards - IEEE Digital Reality standards

- nominees/apache-fineract.json
- nominees/avyantra-health-technologies.json
- nominees/project-aedes.json
> Update Contact Info

- docs/help-center/best-practices.md
> Update best practices 

- nominees/kiva-protocol.json
> Update DPG: Kiva Protocol

- digitalpublicgoods/farmstack.json
Update open standards indicators et al.
> Update DPG: Farmstack

- help-center/best-practices.md
> Update best practices

- digitalpublicgoods/odk.json
Update broken community guidelines link and blank spaces that caused some links to not display properly in the registry
> Update DPG: ODK

- digitalpublicgoods/divoc.json
Privacy link update:
Original link pointed to a possible implementation not directly to the digital solution privacy policy.
> Update DPG: DIVOC

- digitalpublicgoods/dhis2.json
New links properly redirect to the corresponding documentation
> Update DPG: DHIS2

- digitalpublicgoods/bahmni.json
This PR adds Code of Conduct found in project documentation for indicator 9c of the DPG Standard:
https://bahmni.atlassian.net/wiki/spaces/BAH/pages/1769406490/Community+Code+of+Conduct
Changes "griefAbuseHarassmentProtection" value and updates "harassmentProtectionSteps" description.
> Update DPG: Bahmni

- digitalpublicgoods/opensrp.json
There are other best practices for development of this digital solution in their documentation like:
- Naming conventions
- Code formatting
- Code commenting
- Others
> Update DPG: OpenSRP

- digitalpublicgoods/openmrs.json
- nominees/openmrs.json
> Update DPG: OpenMRS

- nominees/openattestation.json
> Update DPG: OpenAttestation

- help-center/dpg-review-policy.md
> Update DPG Review Policy

- digitalpublicgoods/openrims.json
> Update DPG: OpenRIMS

- digitalpublicgoods/openrims.json
- nominees/openrims.json
Update alias - remove Pharmadex
> Update alias - remove Pharmadex

- nominees/deon.json
> Update nominee: Deon

- help-center/best-practices.md
- help-center/open-standards.md
**Update open standards list:**
- [ISO/IEC 27018:2019](https://www.iso.org/standard/76559.html) - is a code of practice that focuses on protection of personal data in the cloud. It is based on ISO/IEC information security standard 27002 and provides implementation guidance on ISO/IEC 27002 controls applicable to public cloud Personally Identifiable Information (PII).
- [ISO 37002:2021](https://www.iso.org/standard/65035.html) - Whistleblowing management systems
**Update best practices list:**
- [OpenSSF Best Practices Badge Program](https://bestpractices.coreinfrastructure.org/en)
> Update open standards/ best practices

- digitalpublicgoods/deon.json
- nominees/deon.json
Hot fix for failing merge into registry for Deon
> [UPDATE] Add DPG: Deon 

- README.md
This PR adds an archive note to the README.md file to notify contributors of the new changes.
Cc: @ricardomiron.
> Add Archive Warning Note
