nominees/open-civil-registration-and-vital-statistics.json

I can see a 404 from the link to the website on https://digitalpublicgoods.net/explore/. I think we need to add ```https://``` here.

Fix 404 error for Open Civil Registration & Vital Statistics

---

.github/workflows/main.yml
README.md
docs/development.md

Fix #54 
Include `[skip pr]` or `[pr skip]` to prevent the CI from automatically open a PR when committing/merging to master

BLD: adds [skip pr] functionality

---

scripts/order-fields.js

In preparation for accepting automatic PR from the revised online submission available at https://digitalpublicgoods.net/submission, a new field is being added to capture the corresponding field from the form on providing evidence for the relevance of this project to the SDGs

BLD: added new field: SDGevidence [skip pr]

---

nominees/openlmis.json
nominees/openmrs-android-client.json
nominees/openmrs-core.json
nominees/openmrs.json

As request by OpenLMIS, updating their listing to only use the short name, and removing the spelling out. 
Did the same for OpenMRS.

MAINT: name updates for OpenLMIS, OpenMRS [skip pr]

---

scripts/push.bash

Propagating the changes introduced in unicef/publicgoods-scripts#6, which adds the generation of website pages for each project that has been screened and has a corresponding file in `screening/*.json`
Cc: @nathanbaleeta

BLD: CI builds HTML for screened dpgs [skip pr]

---

nominees/apache-fineract.json
nominees/opencrvs.json
nominees/primero.json
nominees/x-road.json

Updating the status of these 4 projects are recently screened Digital Public Goods (DPGs):
* Apache Fineract (#111)
* OpenCRVS (#90)
* Primero (#93)
* X-Road (#113)

BLD: updated DPG stage for 4 projects

---

screening-schema.json
screening/apache-fineract.json
screening/mifos-community-app.json
screening/opencrvs.json
screening/openg2p.json
screening/primero.json
screening/x-road.json

Fixed typo error in screening schema: updated field `developmentcounties` to  `developmentCountries` and cascaded changes to all projects under screening.

Fixed typo error in screening schema

---

nominees/wonder-tree.json

Added `repositoryURL` that we missed in #127

MAINT: add missing repoURL [skip pr]

---

package-lock.json
package.json

Missing package [dotenv](https://www.npmjs.com/package/dotenv) required [here](https://github.com/unicef/publicgoods-candidates/blob/8b62f1b10c31bd71064e9cab2d818a579b6ac204/scripts/api.js#L13).
The previous CI build failed for [this reason](https://github.com/unicef/publicgoods-candidates/runs/1824452824?check_suite_focus=true#step:5:10), and this PR adds the missing dependency.

BUG: fix missing dep in #317

---

nominees/project-connect.json

The license link was not pointing to the actual LICENSE file in the repo. Fixed
The `[skip pr]` label is to skip the automatic opening of a PR to propagate these changes to `publicgoods/products` since this change has already been manually pushed there in publicgoods/products#100

MAINT: update license link [skip pr]

---

nominee-schema.json
nominees/met-norway-weather-api.json

Removed `NLOD-1.0` license from `MET Norway Weather API` licensing list.

Removed NLOD-1.0 license from MET Norway licensing list

---

CONTRIBUTING.md

fix issue #388 
Updated links in [CONTRIBUTING.md ](https://github.com/unicef/publicgoods-candidates/blob/master/CONTRIBUTING.md)
now they are relevant to this project

fix wrong links in CONTRIBUTING file

---

nominees/aleph.json

The goal of the Aleph project is to provide powerful technology to investigative journalists who want to track (mainly) [white collar crime](https://en.wikipedia.org/wiki/White-collar_crime). The development is fully open, and coordinated by the data team at the Organized Crime and Corruption Reporting Project.
With Aleph journalists can search and cross-reference more than one billion records to trace criminal connections and patterns and efficiently collaborate across borders.

add nominee: Aleph

---

CONTRIBUTING.md
README.md

This PR is for open ended issue in #473
I found that in current repo and site little information about what are UN's SDGs. Right now new contributors need to Google it.
I added relevant links to `sdgs.un.org/goals` in `README.md` and `CONTRIBUTING.md`. Hope it'll help)

Add links to sdg goals [skip pr]

---

CONTRIBUTING.md

This contribution is for the open-ended issue in #473.
Initially I made a lot of errors while trying to nominate a Digital Public Good and was unable to understand the reason for the error and how to debug it. I have added some additional information in the `Validate your submission` section so that new contributors find it easier to debug if the CI build fails when they are submitting the PR.

Add information about debugging errors

---

nominees/openbci-gui.json

OpenBCI stands for open-source brain-computer interface (BCI). They provide anyone with a computer, the tools necessary to sample the electrical activity of their body.
OpenBCI specializes in creating low-cost, high-quality biosensing hardware for brain computer interfacing. Their arduino compatible biosensing boards provide high resolution imaging and recording of EMG, ECG, and EEG signals. Their devices have been used by researchers, makers, and hobbyists in over 80 countries as brain computer interfaces to power machines and map brain activity. OpenBCI headsets, boards, sensors and electrodes allow anyone interested in biosensing and neurofeedback to purchase high quality equipment at affordable prices.

add nominee: brain-computer interfacing

---

digitalpublicgoods/divoc.json
nominees/divoc.json

Encode `DIVOC` full submission into `JSON`

Encode DIVOC full submission into JSON

---

digitalpublicgoods/starhealth.json

Encode `StarHealth` full submission into `JSON`

Encode StarHealth full submission into JSON

---

scripts/push.bash

Connected repo [unicef/publicgoods-scripts](https://github.com/unicef/publicgoods-scripts/) switched to a monorepo structure managed through npm@7 workspaces. The folder structure and relative paths changed, so this PR propagates the changes needed so as not to break integration in the CI.

BLD: propagating unicef/publicgoods-scripts#19

---

.github/workflows/main.yml

Follow up to #578, fixes the CI by upgrading the version of Node to 16

MAINT: update CI to Node v16

---

.github/workflows/auto.yml

Follow up to #580 and #578, fixes the CI by upgrading the version of Node to 16.
There are two different GitHub Actions workflows: #580 fixed the one that runs on every commit to master (`main.yml`), this PR fixes the one that runs nightly on a cronjob at midnight GMT (`auto.yml`).

BUG: update CI to Node v16

---

scripts/push.bash

Includes the generation of `/eligibility` page on the public website, which was introduced in unicef/publicgoods-scripts#18

MAINT: propagate unicef/publicgoods-scripts#18

---

nominee-schema.json

Remove trailing space in license entry in `nominee-schema.js`

MAINT: removed extra space

---

.github/workflows/auto.yml
.github/workflows/main.yml

Fixing my oversight in recently addressing #617, and requiring updating the CI scripts that run only on the `main` branch

MAINT: update branch name to main in CI

---

digitalpublicgoods/standard-for-public-code.json

Add DPG: Standard for Public Code

---

scripts/push.bash

Continues the propagation of changes started in #661, which otherwise causes the CI to fail after updating the primary branch name from `master` to `main` as per #617

BUG: fix CI script, update branch name

---

nominees/ai-agro.json

The name `OpenAgro` was taken, so `Rentadrone.cl` (the product owner) registered a new name: `AI Agro`

Update nominee: OpenAgro to AI Agro

---

.github/workflows/auto.yml
.github/workflows/main.yml
scripts/push.bash

Propagating the changes for unicef/publicgoods-scripts#62 since the CI of this repo (publicgoods-candiadates) is the process that does the rebuild of the public website.
I confirm that the following two variables have been added as secrets to this repository:
* `NEXT_PUBLIC_MAPBOX_TOKEN`
* `NEXT_PUBLIC_SHEET_ID`

BLD: propagating changes to add map to website

---

digitalpublicgoods/altinn.json

We've restructured our documentation site, [docs.altinn.studio](https://docs.altinn.studio/) with better language support and better and more readable links.

Updated links in altinn.json

---

package-lock.json
package.json
scripts/order-fields.js

While investigating #716, we come up with a limitation of the CI that is not explicit enough where there is a discrepancy in the order of the fields in any submission. This PR addresses that shortcoming by including a colored diff of the problem, as per the screenshot below:

MAINT: more verbose output in error in order-fields.js

---

package.json

GitHub Actions support colored output in their logs, yet, the way each command in invoked through a sub-shell using bash creates an environment that is not identified as a proper TTY, and without color support. Then, when the `order-fields.js` script relies on the `colors` package to automatically detect whether the output terminal supports colors or not, it detects it doesn't and does not produce color-enabled output. Knowing that indeed the output supports color, this PR forces the code to output color, which results in the expected output. See #734's [failed CI run](https://github.com/unicef/publicgoods-candidates/runs/3724747847) for a colored output.
#734 was opened for testing purposes only; the correct flow is:

MAINT: force color in output of order fields script

---

nominees/feed-the-monster.json
nominees/global-digital-library.json
nominees/statbus.json
nominees/vrapeutic.json

Update broken links for the following DPGs:
- [Feed The Monster](https://www.feedthemonsterapp.com/)
- [Global Digital Library](https://digitallibrary.io)
- [Vrapeutic](https://myvrapeutic.com/)
- [Statbus](https://www.statbus.org/)
- [Bisa Health](https://bisaapp.com/)
- [Accessible Kazakhstan](https://doskaz.kz/en)

Update Broken Website Links For DPGs in Registry

---

scripts/push.bash

This PR introduces a very small but practical change: whenever @SarahWat or @Not-Whiskey create a new page in the Heroku Wordpress instance, the deployment of https://digitalpublicgoods.net will automatically add them and publish them, whereas before they had to be manually added (usually by me). 
By running `git add .`, git will add all new files in that (website) folder. I have tested this successfully in my local environment.

BLD: automatic addition of new website pages

---

nominees/lily-the-llama-helps-her-herd.json

Digital public goods must use an open license. Lily the Llama Helps Her Herd prior to this update was using a license that was not part of the approved OSI Licenses. This pull request addresses that issue by updating from `CC-BY-NC-ND 4.0` to `CC-BY-NC-SA-4.0`

Update nominee: Lily the Llama Helps Her Herd

---

digitalpublicgoods/lookingglass.json

There was a mismatch between the naming of the files of `nominees/lookingglass.json` and `digitalpublicgoods/looking-glass.json` (note the `-` difference) that was causing the build to fail. This fixes it.

BUG: rename lookingglass

---

nominee-schema.json

This PR addresses an issue in #958. 
FYI - Version 3.0 of the license carries the SPDX identifier [OGL-UK-3.0](https://en.wikipedia.org/wiki/Open_Government_Licence) as indicated in the license section.

Add license: OGL-UK-3.0

---

nominees/feed-the-monster.json

Feed the Monster was approved in the first round as an exception. This was also discussed the first time Feed the Monster was vetted as a DPG, at that point the standard was still very much under development and Feed the Monster was approved. As the standard is defined today, it is not within the standard to use Unity.
But, this problem will be “fixed” for FTM when it is re-implemented as H5P, where the entire platform is open source. In the meantime this PR relegates the status back to `nominee`.

Relegate DPG: Feed the Monster

---

digitalpublicgoods/rapidpro.json

FAQs link was update to a different URL

Update DPG: RapidPro

---

digitalpublicgoods/kobotoolbox.json

Update privacy policy links, one of them was no longer available and main page refers to the main policy on the website which is already here.

Update DPG: Kobotoolbox

---

digitalpublicgoods/mojaloop.json

Remove ownership evidence link that is no longer available, terms of use are still valid and serve this purpose.

Update DPG: Mojaloop

---

.github/workflows/main.yml

Bumping file-changes-action to v1.2.4 in order to address a discovered bug when looking for changes in file names.
This can be seen in the recent build failures for the DPG API in [this action output](https://github.com/DPGAlliance/publicgoods-candidates/actions/runs/3424786677/jobs/5705009462#step:3:1) as archived nominees from [this commit](https://github.com/DPGAlliance/publicgoods-candidates/pull/1456) are seen a name change which triggered the error.
The related issue for this can be seen [here](https://github.com/trilom/file-changes-action/issues/100)
This merge would only affect the building of the DPG API as it is the only thing currently being affected during deployment.

Update GitHub action file-changes-action to v1.2.4

---

scripts/push.bash

This PR:
- Updates `push.bash` build script to that of the new build process from the `publicgoods-scripts` repository.

Updated push script to match new registry build updates

---

scripts/push.bash

Temporarily disabling build of maps package as it is causing deployment errors

disable map build

---

.github/workflows/auto.yml

This PR:
- Deprecates the current nightly build process for the DPG website using this `publicgoods-candidates` repo
- This is in favour of a new deployment process which would center around the `publicgoods-scripts` repo
- The current actions script would be present in the new process in the `publicgoods-scripts` repo

Deprecate actions workflow for new deployment process
